# Generated by Django 4.2.25 on 2026-01-08 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_variation"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="variation",
            table="variation",
        ),
    ]
