# Generated by Django 4.2.25 on 2026-01-12 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_productgallery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productgallery",
            options={
                "verbose_name": "productgallery",
                "verbose_name_plural": "product gallery",
            },
        ),
        migrations.AlterModelTable(
            name="productgallery",
            table="productgallery",
        ),
    ]
