# Generated by Django 6.0 on 2026-01-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="account",
            table="account",
        ),
    ]
