# Generated by Django 4.2.25 on 2026-01-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_account_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
